### ISSUE TITLE
Build fails 

### ISSUE THREAD

**Issue by leath-dub** [batiati/mustache-zig#15]
I am trying to build the library, in the git root I run `zig build` and get the following output
```zig
src/ffi/extern_types.zig:51:10: error: extern structs cannot contain fields of type
'?fn(?*const anyopaque, *const ffi.extern_types.Path, *ffi.extern_types.UserData) ca
llconv(.C) ffi.extern_types.PathResolution'
    get: ?fn (user_data_handle: UserDataHandle, path: *const Path, out_value: *UserD
ata) callconv(.C) PathResolution,
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/ffi/extern_types.zig:51:10: note: only pointer like optionals are extern compati
ble
referenced by:
    UserData: src/ffi/extern_types.zig:49:29
    UserData: src/ffi/extern_types.zig:51:80
    remaining reference traces hidden; use '-freference-trace' to see all reference
traces

src/parsing/parser.zig:140:68: error: expected type '*parsing.text_part.TextPart(.{.
source = .{ .string = .{.copy_strings = true} }, .output = .cache, .features = .{.al
low_redefining_delimiters = true, .preseve_line_breaks_and_indentation = true, .lamb
das = .{ .enabled = .{ ... } }}
```
Incidently I am trying to also get it working as a package, how can I statically link the library into my zig project ( can they be built a long side one another ? ). Sorry I am new to zig :).

**Comment by batiati** [comment]
Hello,

Currently, we still need to build with Zig stage1 compiler, so if you're using Zig 0.10.1, you can build using `-fstage1` flag.
If you want to try Zig master, you may want to use the branch named `stage3`, which isn't 100% working, but can build and run most examples and benchmarks using the stage3 compiler.

> Incidently I am trying to also get it working as a package, how can I statically link the library into my zig project ( can they be built a long side one another ? ). 

Sure, take a look at the [benchmark project](https://github.com/batiati/mustache-zig/blob/master/benchmark/build.zig), it uses mustache-zig as a Zig package; And take another look at the [C sample build](https://github.com/batiati/mustache-zig/blob/f59cbb63fb6b7c6803f17ffc307c306e1d012046/build.zig#L45-L64), it uses as an static library.

> Sorry I am new to zig :).

Have fun!

**Comment by leath-dub** [comment]
Thanks, your a great intro to the zig community :)

**Comment by leath-dub** [comment]
> Currently, we still need to build with Zig stage1 compiler, so if you're using Zig 0.10.1, you can build using -fstage1 flag.
it sais `-fstage1` is not a valid option, also I did add the package as in the benchmark but building my project still fails with this
```zig
Currently, we still need to build with Zig stage1 compiler, so if you're using Zig 0.10.1, you can build using -fstage1 flag.
```

**Comment by batiati** [comment]
Can you confirm your version? 

```bash
zig version
0.10.1
```

In order to use `-fstage1`, you have to use Zig version 0.10.0 or 0.10.1.

Zig 0.11.0-dev has dropped the stage1 compiler. For using this Zig version, please clone the branch named stage3: https://github.com/batiati/mustache-zig/tree/stage3, and be aware that you may face some compiler errors.

**Comment by leath-dub** [comment]
> Can you confirm your version?
> 
> ```shell
> zig version
> 0.10.1
> ```
> 
> In order to use `-fstage1`, you have to use Zig version 0.10.0 or 0.10.1.
> 
> Zig 0.11.0-dev has dropped the stage1 compiler. For using this Zig version, please clone the branch named stage3: https://github.com/batiati/mustache-zig/tree/stage3, and be aware that you may face some compiler errors.

ahh that must be it, im on dev version

**Comment by bobf** [comment]
@batiati Did you have any interest in making this work with Zig 0.12.x ?

I started here: https://github.com/batiati/mustache-zig/compare/stage3...bobf:mustache-zig:stage3 but I am pretty new to Zig so I am not too confident about my changes.

There are still compiler errors, but I have fixed a lot of them.
