### ISSUE TITLE
Windows Support

### ISSUE THREAD

**Issue by theseyan** [batiati/mustache-zig#2]
Hi, I'm excited to use this library in my Zig project.
Is there an estimate for how long it would take to implement full Windows support?

**Comment by batiati** [comment]
Hello @theseyan

Depending on your use case it should work just fine. The main issue supporting Windows for now is a weird segfault during lambda expansion.

`zig build test` will fail on Windows, but I think the `benchmark` and `samples` projects can run without issues.

Let me know what features you need in your use case so I can include some working examples for Windows.
